In [1]:
import numpy as np

In [71]:
num_states = 2**4
num_neurons = 8

data = np.random.randint(2, size=(num_states, num_neurons))

In [72]:
data

array([[0, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1]])

In [73]:
T = np.dot((2*data.T-1),(2*data - 1)) - num_states * np.identity(num_neurons)

In [74]:
state = np.random.randint(2, size=(num_neurons,))
state

array([1, 0, 0, 0, 1, 1, 1, 0])

In [75]:
for i in range(1000):
    state = sigmoid(np.dot(T, state))
np.round(state)

array([ 1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.])

In [31]:
def sigmoid(X):
    return 1. / (1. + np.exp(-X))

def sigmoid_grad(X):
    return sigmoid(X) * ( 1 - sigmoid(X) )

In [ ]:
class Neuron(object):
    def __init__(self):
        pass